name             'pw_git_repo'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures pw_git_repo'
long_description 'Installs/Configures pw_git_repo'
version          '0.1.0'
